### ISSUE TITLE
Inference with another video?

### ISSUE THREAD

**Issue by levanpon98** [zczcwh/PoseFormer#7]
Hi,

This project is very interesting. So how can I run it with own video

Thanks

**Comment by zczcwh** [comment]
@levanpon98  Right now I don't have time to clean up my code for inference in-the-wild videos. You can refer to Videopose3d (https://github.com/facebookresearch/VideoPose3D/blob/master/INFERENCE.md). 
But I follow another repo (https://github.com/zh-plus/video-to-pose3D). If you want to use our model based on their code, you need to modify some files. Also, the pre-trained model used for inference is different from what I provided. Because the provided model is based on Human3.6M 2D joints (17 joints). While if inference in-the-wild video, the 2D pose detector such as HRNet or AlphaPose will return 2D joints as Coco format. Maybe I will clean up the code and release the pre-trained model for inference in-the-wild video when I have time.

**Comment by puppet101** [comment]
@zczcwh How about the progress of the inference code? Could you please share your pre-trained model based on 2d joints of Coco format?
